# Generated by Django 5.2.11 on 2026-06-12 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_carga', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('juego_id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('link', models.URLField()),
                ('imagen', models.URLField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('peak_jugadores', models.IntegerField()),
                ('precio', models.FloatField(blank=True, null=True)),
                ('desarrolladores', models.ManyToManyField(to='main.desarrollador')),
                ('etiquetas', models.ManyToManyField(to='main.etiqueta')),
                ('usuarios_gustan', models.ManyToManyField(related_name='juegos_gustados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
